# --- General options --- #

# Name of website
title: <i class='fa fa-rocket' style='color:black'></i> LubeVPN

# Short description of your site
description: Proxy Service Based on Fully Decentralized Citium

# --- Local development options ---
# If your website is hosted locally rather than on GitHub, then you need to uncomment the next two parameters to set the url and baseurl
# *** If you're not sure what this mean, then leave this section as it is. Only modify the url and baseurl if you know what you're doing!***

# url is the the website domain URL without a trailing slash
#url: "https://example.com"

# baseurl should be an empty string
#baseurl: ""

# --- Navigation bar options --- #

# List of links in the navigation bar
navbar-links:
#  繞過萬里網審<br>Circumvention: "circumvention"
#  絕不寫Log政策<br>No Log Policy: "no_log_policy"
#  開天闢地的技術<br>Technology: "technology"
#  去中心化網絡<br>Citium: "citium"
  推薦人計劃<br>Referral: "referral"
  免費試用<br>Install Trial: "installation"
#  產品服務亮點<br>Service Features:
#    - 繞過萬里網審<br>Circumvention: "circumvention"
#    - 匿名和隱私<br>Anonymity: "anonymity_privacy"
#    - 開天闢地的技術<br>Technology: "technology"
#    - 絕不寫Log政策<br>No Log Policy: "no_log_policy"
  產品服務支持<br>Support:
    - Windows版本安裝<br>Windows Version: "windows"
    - 續時抵值：加密幣<br>Payment by Crypto: "#-%E7%BA%8C%E6%99%82%E6%8A%B5%E5%80%BC%E5%8A%A0%E5%AF%86%E5%B9%A3by-cryptocurrency"
    - 續時抵值：中港常用<br>Payment by RMB/HKD: "#-%E7%BA%8C%E6%99%82%E6%8A%B5%E5%80%BC%E4%B8%AD%E6%B8%AF%E5%8F%B0%E5%B8%B8%E7%94%A8by-membership-credits"
    - 續時抵值：卡密卡劵<br>Payment by Cards: "payment_cards"
    - 聯繫我們<br>Contact Us: "contact_us"
  西蒂姆P2P網絡<br>Citium:
    - 為何用西蒂姆？<br>Citium's for?: "citium_what_for"
    - 可抵賴可推诿<br>Deniability: "deniability"
    #- 無需准入或許可<br>Permissionless: "permissionless"
    #- 可推諉身份驗證性<br>Authentication: "authentication"
    #- 分身馬甲帳號<br>Sockpuppetry: "sockpuppetry"
    - 機密|完整|可用性<br>Conf.|Int.|Avai.: "confidentiality"
    #- 可用性<br>Availability: "availability"
    - 不可靠的中心化<br>Fallibility: "fallible_providers"


#    - Learn markdown: "http://www.markdowntutorial.com/"
#  Author's home: "http://deanattali.com"
###############################################################################

# Image to show in the navigation bar - image must be a square (width = height)
# Remove this parameter if you don't want an image in the navbar
# avatar: "/img/LubeVPN_logo_square.png"

# If you want to have an image logo in the top-left corner instead of the title text,
# then specify the following parameter
# title-img: "/img/LubeVPN_logo_square.png"

# --- Background colour/image options --- #

# Personalize the colors in your website. Colour values can be any valid CSS colour

navbar-col: "#F5F5F5"
navbar-text-col: "#404040"
navbar-children-col: "#F5F5F5"
page-col: "#FFFFFF"
link-col: "#008AFF"
hover-col: "#0085A1"
footer-col: "#F5F5F5"
footer-text-col: "#777777"
footer-link-col: "#404040"

# Alternatively, the navbar, footer, and page background can be set to use background images
# instead of colour

# navbar-img: "/img/bgimage.png"
# footer-img: "/img/bgimage.png"
# page-img: "/img/bgimage.png"

# --- Footer options --- #

# Change all these values or delete the ones you don't want.
# Important: you must keep the "name" parameter, everything else you can remove
author:
  name: Rainbow Unicorn Team (RUT)

# Select your active Social Network Links.
# Uncomment the links you want to show in the footer and add your information to each link.
# You can reorder the items to define the link order.
# If you want to add a new link that isn't here, you'll need to also edit the file _data/SocialNetworks.yml
social-network-links:
#  rss: false
  email: "LubeVPN@gmail.com"
  facebook: LubeVPN
  github: LubeVPN
  twitter: LubeVPN
  reddit: LubeVPN
#  linkedin: daattali Waiting for the Company page to be created
#  xing: yourname
  stackoverflow: "12997529/lubevpn"
#  snapchat: deanat78
  instagram: lubevpn
#  youtube: user/deanat78
#  spotify: yourname
#  telephone: +14159998888
#  steam: deanat78
#  twitch: yourname
#  yelp: yourname

# Select which share links to show in posts
share-links-active:
  twitter: true
  facebook: true
  linkedin: false

# How to display the link to the website in the footer
# Remove this if you don't want a link in the footer
url-pretty: "LubeVPN.com"  # eg. "deanattali.com/beautiful-jekyll"

# --- Web Statistics Section --- #

# Fill in your Google Analytics gtag.js ID to track your website using gtag
#gtag: ""

# Fill in your Google Analytics ID to track your website using GA
#google_analytics: ""

# Google Tag Manager ID
#gtm: ""

# Matomo (aka Piwik) Web statistics
# Uncomment the following section to enable Matomo. The opt-out parameter controls
# whether or not you want to allow users to opt out of tracking.

#matomo:
#  site_id: "9"
#  uri: "demo.wiki.pro"
#  opt-out: true

# --- Comments --- #

# Fill in your Disqus shortname (NOT the userid) if you want to support Disqus comments
# disqus: ""

# If you want to use JustComments fill with the API Key
#just-comments: "ABCD-EFGH-IJKL"

# To use Facebook Comments, fill in a Facebook App ID
# fb_comment_id: ""

# To use Staticman comments, fill in repository, branch, and endpoint
staticman:
  repository : # GitHub username/repository eg. "daattali/beautiful-jekyll"
  branch     : master # If you're not using `master` branch, then you also need to update the `branch` parameter in `staticman.yml`
  endpoint   : # URL of your own deployment, with a trailing slash (will fallback to a public GitLab instance) eg. https://<your-api>/v3/entry/github/
  reCaptcha:
    # reCaptcha for Staticman (OPTIONAL, but recommended for spam protection)
    # If you use reCaptcha, you must also set these parameters in staticman.yml
    siteKey  : # Use your own site key, you need to apply for one on Google
    secret   : # ENCRYPT your password by going to https://staticman3.herokuapp.com/v3/encrypt/<your-site-secret>

# --- Misc --- #

# Facebook App ID
# fb_app_id: ""

# Excerpt Word Length
# Truncates the excerpt to the specified number of words on the index page
excerpt_length: 10

# Character used to separate site title and description in HTML document title
# and RSS feed title
title-separator: "-"

# Ruby Date Format
date_format: "%B %-d, %Y"

# --- Don't need to touch anything below here (but you can if you want) --- #

# Output options (more information on Jekyll's site)
timezone: "America/Vancouver"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5
paginate_path: "/blog/page:num/"

kramdown:
  input: GFM
  footnote_nr: 1
  hard_wrap: false

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true  # add comments to all blog posts
      social-share: true # add social media sharing buttons to all blog posts
  -
    scope:
      path: "" # all files
    values:
      layout: "page"
      show-avatar: true

# Use tags index page and make tags on each post clickable
link-tags: true

# Exclude these files from production site
exclude:
  - CHANGELOG.md
  - CNAME
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - Vagrantfile

# prose.io config
prose:
  rooturl: '_posts'
  media: 'img'
  ignore:
    - 404.html
    - LICENSE
    - feed.xml
    - _config.yml
    - /_layouts
    - /_includes
    - /css
    - /img
    - /js
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Post title"
          placeholder: "Title"
          alterable: true
      - name: "subtitle"
        field:
          element: "textarea"
          label: "Subtitle"
          placeholder: "A description of your post."
          alterable: true
      - name: "date"
        field:
          element: "text"
          label: "Date"
          help: "Enter date of post."
          placeholder: "yyyy-mm-dd"
          alterable: true
      - name: "image"
        field:
          element: "text"
          label: "Image"
          help: "Add a thumbnail image to your post."
          placeholder: "Thumbnail"
          alterable: true
      - name: "published"
        field:
          element: "checkbox"
          label: "Publish"
          help: "Check to publish post, uncheck to hide."

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji

# Beautiful Jekyll / Dean Attali
# 2fc73a3a967e97599c9763d05e564189
